(function(root){'use strict';
function rect(r){if(Array.isArray(r))return r;return [r?.x??0,r?.y??0,r?.width??r?.w??0,r?.depth??r?.height??r?.h??0];}
function project(p,c){const dx=p[0]-c.target[0],dy=p[1]-c.target[1],dz=p[2]-c.target[2];const x=dx*Math.cos(c.yaw)-dy*Math.sin(c.yaw),q=dx*Math.sin(c.yaw)+dy*Math.cos(c.yaw);return [c.width/2+c.pan[0]+x*c.scale,c.height/2+c.pan[1]-(dz*Math.cos(c.pitch)-q*Math.sin(c.pitch))*c.scale,q*Math.cos(c.pitch)+dz*Math.sin(c.pitch)];}
function inside(p,poly){let hit=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const a=poly[i],b=poly[j];if((a[1]>p[1])!==(b[1]>p[1])&&p[0]<(b[0]-a[0])*(p[1]-a[1])/(b[1]-a[1])+a[0])hit=!hit;}return hit;}
function boxFaces(bounds,c,meta,color){const [x,y,z,w,d,h]=bounds;const pts=[[x,y,z],[x+w,y,z],[x+w,y+d,z],[x,y+d,z],[x,y,z+h],[x+w,y,z+h],[x+w,y+d,z+h],[x,y+d,z+h]].map(p=>project(p,c));return [[0,1,5,4],[1,2,6,5],[2,3,7,6],[3,0,4,7],[4,5,6,7]].map((indices,i)=>({points:indices.map(n=>pts[n]),depth:indices.reduce((s,n)=>s+pts[n][2],0)/4,meta,color,shade:[.7,.8,.88,.76,1][i]}));}
function shade(hex,f){return '#'+hex.slice(1).match(/../g).map(v=>Math.round(parseInt(v,16)*f).toString(16).padStart(2,'0')).join('');}
const api={rect,project,inside,boxFaces};if(typeof module!=='undefined'&&module.exports)module.exports=api;if(!root.document)return;
const doc=root.document,$=id=>doc.getElementById(id),data=root.SPATIAL_DATA||{},sites=data.sites||[],canvas=$('scene'),ctx=canvas.getContext('2d');let faces=[],selected=null;const camera={yaw:-.65,pitch:.62,scale:4,target:[0,0,0],pan:[0,0],width:800,height:600};
function node(tag,text){const e=doc.createElement(tag);if(text!==undefined)e.textContent=String(text);return e;}
function currentSite(){return sites.find(s=>s.id===$('site').value)||sites[0];}function currentBuildings(){const s=currentSite();return (s?.buildings||[]).filter(b=>!$('building').value||b.id===$('building').value);}
function path(value){if(!value)return null;const p=typeof value==='string'?value:value.path;if(!p||/^\w+:/.test(p)||p.startsWith('//'))return null;return p.startsWith('geospatial/maps/')?p.slice(16):p.startsWith('geospatial/')?'../'+p.slice(11):p.startsWith('enterprise/')?'../../'+p:p;}
function links(target,items){target.replaceChildren();Object.entries(items||{}).forEach(([name,value])=>{const href=path(value);if(href){const a=node('a',name.replaceAll('_',' '));a.href=href;target.append(a);}});}
function fit(){const buildings=currentBuildings();let bounds;if(buildings.length){const rs=buildings.map(b=>rect(b.rect_m));bounds=[Math.min(...rs.map(r=>r[0])),Math.min(...rs.map(r=>r[1])),Math.max(...rs.map(r=>r[0]+r[2])),Math.max(...rs.map(r=>r[1]+r[3]))];}else{const e=currentSite()?.envelope_m;const r=Array.isArray(e)?e: [e?.width||100,e?.depth||100];bounds=[0,0,r[0]||100,r[1]||100];}camera.target=[(bounds[0]+bounds[2])/2,(bounds[1]+bounds[3])/2,0];camera.scale=Math.min(camera.width/(bounds[2]-bounds[0]+35),camera.height/(bounds[3]-bounds[1]+35))*.75;camera.pan=[0,0];draw();}
function roomColor(r){const t=((r.kind||'')+' '+(r.name||'')).toLowerCase();return /residen|bed|teach|class|learn/.test(t)?'#b6c1ac':/support|service|meeting|lobby|kitchen|core|circulation/.test(t)?'#d5c8ac':'#a8bcc4';}
function addBox(b,meta,color){faces.push(...boxFaces(b,camera,meta,color));}
function draw(){if(!ctx)return;ctx.clearRect(0,0,camera.width,camera.height);ctx.fillStyle='#e8e9e2';ctx.fillRect(0,0,camera.width,camera.height);faces=[];
if(!$('building').value){const site=currentSite(),env=site?.envelope_m;if(Array.isArray(env)){const points=[[0,0,0],[env[0],0,0],[env[0],env[1],0],[0,env[1],0]].map(p=>project(p,camera));ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1]));ctx.closePath();ctx.fillStyle='#dedfd4';ctx.fill();ctx.setLineDash([5,5]);ctx.strokeStyle='#9ba99b';ctx.stroke();ctx.setLineDash([]);}Object.entries(site?.access||{}).forEach(([key,value])=>{if(!key.endsWith('_m')||!Array.isArray(value)||!Array.isArray(value[0]))return;ctx.beginPath();value.forEach((v,i)=>{const p=project([v[0],v[1],.02],camera);i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1]);});ctx.strokeStyle=/fire|service/.test(key)?'#a2957f':'#8babb5';ctx.lineWidth=/fire/.test(key)?4:2;ctx.stroke();});}
const bs=currentBuildings(),peel=Number($('peel').value),gap=Number($('explode').value);const floorCount=Math.max(1,...bs.map(b=>(b.floors||[]).length));$('peel-label').textContent=Math.min(peel,floorCount)+' of '+floorCount+' levels';$('explode-label').textContent=gap+' m additional spacing';
bs.forEach(b=>{const [x,y,w,d]=rect(b.rect_m),floors=b.floors||[];if(!floors.length){addBox([x,y,0,w,d,b.height_m||1],{building:b},'#b6b8ae');return;}floors.slice(0,peel).forEach((f,i)=>{const z=(f.z_m??i*(f.height_m||3.6))+i*gap,h=f.height_m||3.6;addBox([x,y,z,w,d,.28],{building:b,floor:f},'#929c98');const rooms=f.rooms||[];if(!rooms.length){addBox([x,y,z+.28,w,d,h-.28],{building:b,floor:f},'#b6b8ae');return;}[...(f.circulation||[]),...(f.cores||[]),...rooms].forEach(r=>{const [rx,ry,rw,rd]=rect(r.rect_m||r.rect);if(rw>0&&rd>0)addBox([x+rx,y+ry,z+.28,rw,rd,r.geometry_role==='partitioned_room'?Math.max(.15,h-.5):.08],{building:b,floor:f,room:r},roomColor(r));});});});
faces.sort((a,b)=>a.depth-b.depth);faces.forEach(face=>{ctx.beginPath();face.points.forEach((p,i)=>i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1]));ctx.closePath();ctx.fillStyle=shade(face.color,face.shade);ctx.fill();ctx.strokeStyle=selected&&face.meta.room===selected.room?'#9d592c':'#596d7060';ctx.lineWidth=selected&&face.meta.room===selected.room?2:0.7;ctx.stroke();});
// Axes are a local reference frame, not geographic parcel coordinates.
const origin=[65,camera.height-65];[[[1,0,0],'E','#527a8b'],[[0,1,0],'N','#6c815d'],[[0,0,1],'Up','#997654']].forEach(([v,label,color])=>{const a=project(camera.target,camera),b=project(camera.target.map((n,i)=>n+v[i]*12),camera);const dx=(b[0]-a[0])/camera.scale*3,dy=(b[1]-a[1])/camera.scale*3;ctx.beginPath();ctx.moveTo(...origin);ctx.lineTo(origin[0]+dx,origin[1]+dy);ctx.strokeStyle=color;ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#243b45';ctx.font='12px sans-serif';ctx.fillText(label,origin[0]+dx+3,origin[1]+dy);});ctx.fillStyle='#50656e';ctx.font='12px sans-serif';ctx.fillText('LOCAL CONCEPT GEOMETRY · METRES',18,25);
}
function contextMap(target,region){if(!region?.features?.length)return;const [x,y,w,h]=region.extent_local_m;const ns='http://www.w3.org/2000/svg',svg=doc.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 1000 650');svg.setAttribute('role','img');svg.setAttribute('aria-label','Real reference context layers; campus placement is not established');svg.style.width='100%';svg.style.background='#e8e9e2';const scale=Math.min(920/w,530/h),offX=(1000-w*scale)/2,offY=55;function line(points,fill,color){const poly=doc.createElementNS(ns,fill?'polygon':'polyline');poly.setAttribute('points',points.map(p=>(offX+(p[0]-x)*scale)+','+(offY+(h-(p[1]-y))*scale)).join(' '));poly.setAttribute('fill',fill?color:'none');poly.setAttribute('stroke',color);poly.setAttribute('stroke-width',fill?'1':'1.7');svg.append(poly);}function geometry(g,color){if(g.type==='LineString')line(g.coordinates,false,color);if(g.type==='MultiLineString')g.coordinates.forEach(v=>line(v,false,color));if(g.type==='Polygon')g.coordinates.forEach(v=>line(v,true,color));if(g.type==='MultiPolygon')g.coordinates.forEach(v=>v.forEach(r=>line(r,true,color)));if(g.type==='GeometryCollection')g.geometries.forEach(v=>geometry(v,color));}region.features.forEach(f=>geometry(f.geometry,/water|river/.test(f.category)?'#b1cad0':/rail/.test(f.category)?'#657579':'#a5ae9b'));function label(value,px,py){const t=doc.createElementNS(ns,'text');t.textContent=value;t.setAttribute('x',px);t.setAttribute('y',py);t.setAttribute('font-size','16');t.setAttribute('fill','#243b45');svg.append(t);}label('REAL REFERENCE CONTEXT · CAMPUS UNSITED',25,28);label('N ↑',920,28);const length=Math.pow(10,Math.floor(Math.log10(w/5)));line([[0,0],[length,0]],false,'#243b45');label(length+' m · '+(region.crs||'projected context'),offX,620);target.append(svg,node('p','Muted blue: water; charcoal: rail/reference lines. All layers retain their source status. No campus footprint is placed on this map.'));}
function details(){const site=currentSite(),b=currentBuildings().length===1?currentBuildings()[0]:null;$('selection-title').textContent=b?.name||site?.name||'No location';$('status').textContent=b?.status||site?.status||'Status unrecorded';$('height-basis').textContent=b?.height_basis||data.height_basis||'Vertical dimensions are modelled planning assumptions, not measured construction.';links($('building-links'),b?.links||{});const empty=!currentBuildings().length;$('empty').hidden=!empty;if(empty){$('empty').replaceChildren(node('h2','Context only'),node('p',site?.exemption||site?.context||site?.reason||'No enterprise building geometry is established for this location.'));}const context=$('context-content');context.replaceChildren();[site?.geometry_basis,site?.geometry_status,site?.context,site?.access,site?.constraints,site?.provenance].filter(Boolean).forEach(v=>context.append(node('p',typeof v==='string'?v:JSON.stringify(v,null,2))));if(!context.children.length)context.append(node('p','No additional context supplied. Consult the source-linked atlas location record.'));const contextual=data.context?.sites?.find(r=>r.site_id===site?.id);if(contextual){context.append(node('p',contextual.limitations));contextMap(context,data.context.regions?.[contextual.region_key]);(contextual.context_links||[]).forEach(m=>{context.append(node('h3',m.title));const holder=node('div');holder.className='links';links(holder,m.files);context.append(holder);});}const anchor=node('a','Location in enterprise atlas');anchor.href='index.html#'+encodeURIComponent(site?.id||'');context.append(anchor);const comparisons=$('comparison-content');comparisons.replaceChildren();const rows=(data.comparisons||[]).filter(r=>!r.site_id||r.site_id===site?.id);if(!rows.length)comparisons.append(node('p','No paired earlier geometry is available for this location. Current model only; no historical shape is inferred.'));rows.forEach(r=>{const box=node('details');box.append(node('summary',r.title||r.id||'Comparison'));Object.entries(r).forEach(([k,v])=>box.append(node('p',k+': '+(typeof v==='object'?JSON.stringify(v):v))));comparisons.append(box);});}
function siteChanged(){const s=currentSite();$('building').replaceChildren();const all=node('option','All buildings');all.value='';$('building').append(all);(s?.buildings||[]).forEach(b=>{const o=node('option',b.name);o.value=b.id;$('building').append(o);});buildingChanged();}
function buildingChanged(){selected=null;$('picked').textContent='Select an exposed room; peel or separate floors to inspect lower levels.';const max=Math.max(1,...currentBuildings().map(b=>(b.floors||[]).length));$('peel').max=max;$('peel').value=max;details();fit();}
(data.sites||[]).forEach(s=>{const o=node('option',s.name);o.value=s.id;$('site').append(o);});$('revision').textContent='Model revision '+(data.revision||'unrecorded')+' · '+sites.length+' locations';$('site').addEventListener('change',siteChanged);$('building').addEventListener('change',buildingChanged);['peel','explode'].forEach(id=>$(id).addEventListener('input',draw));$('reset').onclick=()=>{camera.yaw=-.65;camera.pitch=.62;$('explode').value=0;fit();};$('top').onclick=()=>{camera.pitch=Math.PI/2;draw();};$('left').onclick=()=>{camera.yaw-=.2;draw();};$('right').onclick=()=>{camera.yaw+=.2;draw();};$('zoom-in').onclick=()=>{camera.scale*=1.2;draw();};$('zoom-out').onclick=()=>{camera.scale/=1.2;draw();};
let dragging=null;const pointers=new Map();canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);pointers.set(e.pointerId,[e.clientX,e.clientY]);dragging={x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,pan:e.shiftKey||e.button===2,moved:false};});canvas.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;const old=pointers.get(e.pointerId),other=[...pointers.entries()].find(([id])=>id!==e.pointerId);if(other){const q=other[1],before=Math.hypot(old[0]-q[0],old[1]-q[1]),after=Math.hypot(e.clientX-q[0],e.clientY-q[1]);if(before>5)camera.scale*=after/before;dragging.moved=true;}else if(dragging){const dx=e.clientX-dragging.x,dy=e.clientY-dragging.y;if(Math.hypot(e.clientX-dragging.startX,e.clientY-dragging.startY)>4)dragging.moved=true;if(dragging.pan){camera.pan[0]+=dx;camera.pan[1]+=dy;}else{camera.yaw+=dx*.008;camera.pitch=Math.max(.12,Math.min(Math.PI/2,camera.pitch+dy*.006));}dragging.x=e.clientX;dragging.y=e.clientY;}pointers.set(e.pointerId,[e.clientX,e.clientY]);draw();});canvas.addEventListener('pointerup',e=>{if(dragging&&!dragging.moved){const r=canvas.getBoundingClientRect(),point=[e.clientX-r.left,e.clientY-r.top];const hit=[...faces].reverse().find(f=>inside(point,f.points));if(hit){selected=hit.meta;const box=$('picked');box.replaceChildren(node('strong',selected.room?.name||selected.floor?.name||selected.building.name));if(selected.room)box.append(node('p','Room '+selected.room.id+' · '+(selected.room.access||'access unrecorded')));if(selected.floor){box.append(node('p','Floor '+selected.floor.id));const target=node('div');target.className='links';links(target,selected.floor.links||{});const a=node('a','Floor in atlas');a.href='index.html#'+encodeURIComponent(selected.floor.id);target.append(a);box.append(target);}draw();}}pointers.delete(e.pointerId);dragging=null;});canvas.addEventListener('pointercancel',e=>{pointers.delete(e.pointerId);dragging=null;});canvas.addEventListener('wheel',e=>{e.preventDefault();camera.scale=Math.max(.1,Math.min(150,camera.scale*Math.exp(-e.deltaY*.001)));draw();},{passive:false});canvas.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','-','='].includes(e.key)){e.preventDefault();if(e.key==='ArrowLeft')camera.yaw-=.1;if(e.key==='ArrowRight')camera.yaw+=.1;if(e.key==='ArrowUp')camera.pitch=Math.min(Math.PI/2,camera.pitch+.1);if(e.key==='ArrowDown')camera.pitch=Math.max(.12,camera.pitch-.1);if(['+','='].includes(e.key))camera.scale*=1.15;if(e.key==='-')camera.scale/=1.15;draw();}});
const tabs=[...doc.querySelectorAll('[role=tab]')];function activate(t){tabs.forEach(x=>{const on=x===t;x.setAttribute('aria-selected',on);x.tabIndex=on?0:-1;$(x.getAttribute('aria-controls')).hidden=!on;});if(t.id==='tab-model')resize();}tabs.forEach((t,i)=>{t.onclick=()=>activate(t);t.onkeydown=e=>{let n;if(e.key==='ArrowRight')n=(i+1)%tabs.length;if(e.key==='ArrowLeft')n=(i+tabs.length-1)%tabs.length;if(n!==undefined){e.preventDefault();activate(tabs[n]);tabs[n].focus();}};});function resize(){const r=canvas.getBoundingClientRect(),dpr=root.devicePixelRatio||1;if(!r.width)return;camera.width=r.width;camera.height=r.height;canvas.width=r.width*dpr;canvas.height=r.height*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);draw();}new ResizeObserver(resize).observe(canvas);resize();siteChanged();
})(typeof window!=='undefined'?window:globalThis);
