"""Render editable SVG/PDF/PNG concept plates from runtime inputs, never as-built plans."""

import argparse
import hashlib
import json
import math
from pathlib import Path
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle
from .model import load, export

NAVY = "#173247"
TEAL = "#1b716d"
GOLD = "#c19343"
PALE = "#eaf1f4"


def build(output):
    output = Path(output)
    output.mkdir(parents=True, exist_ok=True)
    data = load()
    result = export(data)
    a = data["capital"]["implementation_assumptions"]
    plt.rcParams.update(
        {
            "font.family": "DejaVu Sans",
            "svg.hashsalt": "PR119-runtime-v1",
            "font.size": 10,
        }
    )
    paths = []

    def plate(
        name,
        title,
        draw,
        limit="Concept only; no engineering approval, assigned provider space or constructed facility.",
    ):
        fig, ax = plt.subplots(figsize=(14, 9))
        fig.patch.set_facecolor("white")
        fig.subplots_adjust(top=0.84, bottom=0.13, left=0.06, right=0.96)
        fig.text(0.06, 0.94, title, fontsize=21, color=NAVY, weight="bold")
        fig.text(
            0.06,
            0.895,
            "SABLE HARBOR  |  2026-09-11  |  SYNTHETIC DESIGN / PROCUREMENT PENDING",
            fontsize=10,
            color=TEAL,
        )
        if name == "12-construction-schedule":
            fig.subplots_adjust(left=0.15, bottom=0.22)
        draw(ax)
        fig.text(0.06, 0.065, limit, fontsize=9, color=NAVY)
        fig.text(
            0.06,
            0.035,
            "Source: runtime_sites / runtime_capital_plan 2026-09-11 • Generated by enterprise/runtime/render.py",
            fontsize=8,
            color="#555555",
        )
        for ext in ("svg", "pdf", "png"):
            path = output / f"{name}.{ext}"
            kw = (
                {"dpi": 140}
                if ext == "png"
                else {"metadata": {"CreationDate": None, "ModDate": None}}
                if ext == "pdf"
                else {"metadata": {"Date": None}}
            )
            fig.savefig(path, **kw)
            if ext == "svg":
                path.write_text(
                    "\n".join(line.rstrip() for line in path.read_text().splitlines())
                    + "\n"
                )
            paths.append(path)
        plt.close(fig)

    def box(ax, x, y, w, h, text, color=PALE):
        ax.add_patch(Rectangle((x, y), w, h, facecolor=color, edgecolor=TEAL, lw=1.5))
        ax.text(
            x + w / 2, y + h / 2, text, ha="center", va="center", fontsize=10, wrap=True
        )

    def topology(ax):
        sizes = {
            r["site"]: r
            for r in result["capacity"]
            if r["scenario"] == "base" and r["year"] == 2027
        }
        ax.set(xlim=(0, 100), ylim=(0, 70))
        ax.axis("off")
        box(
            ax,
            2,
            38,
            29,
            23,
            f"Switch Tahoe Reno\nSelected transitional primary\nNo contract / reservation\n{sizes['RENO']['peak_kw']} kW base design peak",
        )
        box(
            ax,
            67,
            38,
            31,
            23,
            f"IDACORE Boise\nSelected recovery\nIndependent bootstrap required\n{sizes['BOISE']['peak_kw']} kW base design peak",
        )
        box(
            ax,
            2,
            3,
            40,
            21,
            "Northern Nevada owned parcel\nLand acquired / preconstruction\n0 kW commissioned",
        )
        box(
            ax,
            62,
            3,
            36,
            21,
            "Immutable + offline copies\nSeparate administration / custody\nNo accepted provider or copy",
        )
        for x1, y1, x2, y2 in [(31, 49, 67, 49), (22, 24, 22, 38), (31, 42, 65, 24)]:
            ax.annotate(
                "",
                xy=(x2, y2),
                xytext=(x1, y1),
                arrowprops=dict(arrowstyle="<->", color=GOLD, lw=2, linestyle="--"),
            )
        ax.text(48, 54, "Planned replication", ha="center", fontsize=9)

    plate("01-topology", "Three-site estate and protected copies", topology)

    def site(ax, current=False):
        ax.set(xlim=(0, 200), ylim=(0, 200), aspect="equal")
        ax.set_xlabel("Concept metres")
        ax.set_ylabel("Concept metres")
        side = (
            next(s for s in data["sites"]["sites"] if s["id"] == "RUNTIME-NN-OWNED-DC")[
                "parcel_acres_planning"
            ]
            * 4046.8564224
        ) ** 0.5
        ax.add_patch(
            Rectangle(
                (10, 10), side, side, fill=False, edgecolor=TEAL, lw=2, linestyle="--"
            )
        )
        if current:
            ax.text(
                100,
                95,
                "ACQUIRED / PRECONSTRUCTION\n\n7.5-acre synthetic envelope\nPlanning anchor 39.5450, -119.4550\n0% vertical construction\nNo shell or commissioned plant",
                ha="center",
                va="center",
                fontsize=15,
                color=NAVY,
            )
        else:
            box(ax, 60, 65, 65, 55, "12,000 sf\nproposed building")
            box(ax, 20, 120, 35, 32, "Power /\ngenerator yard")
            box(ax, 132, 95, 35, 42, "Cooling /\nheat rejection")
            box(ax, 65, 20, 85, 25, "Receiving / fire access / service apron")
            box(ax, 20, 55, 30, 50, "Future\nexpansion")
            box(ax, 60, 130, 68, 22, "Drainage / setback reserve")
            ax.annotate("Fiber entry A", xy=(10, 150), xytext=(0, 162), color=TEAL)
            ax.annotate("Fiber entry B", xy=(184, 25), xytext=(130, 5), color=TEAL)

    plate(
        "02-current-condition",
        "Owned site: September 2026 current condition",
        lambda ax: site(ax, True),
        "Synthetic planning envelope, not a survey or real parcel claim. No building or vertical construction exists in this case view.",
    )
    plate(
        "03-site-concept",
        "Proposed owned campus: land-use relationships",
        site,
        "Relationship diagram, not scaled cadastral/civil design. Exact 7.5-acre geometry is independently generated in runtime_parcel.geojson.",
    )

    def floor(ax):
        rooms = a["rooms"]
        total = sum(r["area_sf"] for r in rooms)
        if total != 12000:
            raise ValueError("Floor program must reconcile to 12,000 sf")
        ax.set(xlim=(0, 120), ylim=(0, 100), aspect="equal")
        ax.set_xlabel("Concept feet")
        ax.set_ylabel("Concept feet")
        # 1,650 sf: two 5-ft perimeter aisles and a 6.5-ft controlled spine, each 100 ft long.
        height = 100
        left_width = 5200 / height
        ax.add_patch(
            Rectangle((0, 0), 120, 100, facecolor="#fff3d6", edgecolor=NAVY, lw=2)
        )
        from .design import floor_rooms

        for room in floor_rooms(a):
            x, y, width, room_height = (room[k] for k in ("x", "y", "width", "height"))
            name = room["name"]
            ax.add_patch(
                Rectangle(
                    (x, y), width, room_height, facecolor=PALE, edgecolor=TEAL, lw=1.2
                )
            )
            label = name.replace(" / ", " /\n") + f"\n{room['area_sf']} sf"
            ax.text(
                x + width / 2,
                y + room_height / 2,
                label,
                ha="center",
                va="center",
                fontsize=7,
            )
            if name in {"Lobby / mantrap", "Receiving / quarantine"}:
                ax.plot(
                    [x + width / 2 - 1.5, x + width / 2 + 1.5], [y, y], color=GOLD, lw=4
                )
                edge = x + width if x < 60 else x
                ax.plot(
                    [edge, edge],
                    [y + room_height / 2 - 1.5, y + room_height / 2 + 1.5],
                    color=GOLD,
                    lw=4,
                )
            elif name in {"Network A", "Network B", "Spares / media"}:
                edge = x if name == "Network A" else x + width
                ax.plot(
                    [edge, edge],
                    [y + room_height / 2 - 1.5, y + room_height / 2 + 1.5],
                    color=GOLD,
                    lw=4,
                )
            else:
                edge = x + width if x < 60 else x
                ax.plot(
                    [edge, edge],
                    [y + room_height / 2 - 1.5, y + room_height / 2 + 1.5],
                    color="#bb3344" if name == "Key room" else GOLD,
                    lw=4,
                )
            if name in {
                "Conventional hall",
                "AI hall",
                "Electrical / UPS",
                "Mechanical / CDU",
            }:
                edge = x if x < 60 else x + width
                ax.plot(
                    [edge, edge],
                    [y + room_height / 2 - 1.5, y + room_height / 2 + 1.5],
                    color=GOLD,
                    lw=4,
                )
        ax.text(
            2.5,
            50,
            "Service / emergency egress",
            rotation=90,
            ha="center",
            va="center",
            fontsize=6,
        )
        ax.text(
            117.5,
            50,
            "Service / emergency egress",
            rotation=90,
            ha="center",
            va="center",
            fontsize=6,
        )
        ax.text(
            8.25 + left_width,
            52,
            "Controlled access spine",
            rotation=90,
            ha="center",
            va="center",
            fontsize=6,
        )

    plate(
        "04-space-block-plan",
        "Proposed 12,000 sf floor plan: one level",
        floor,
        "Gold: proposed doors; red: separate key access. Circulation 1,650 sf. Egress overrides access locks; licensed fire/code/structural review required.",
    )

    def chain(ax, labels):
        ax.set(xlim=(0, 100), ylim=(0, 70))
        ax.axis("off")
        for n, label in enumerate(labels):
            col = n % 3
            row = n // 3
            x = col * 34
            y = 48 - row * 32
            box(ax, x, y, 30, 20, label)
            if col < 2 and n < len(labels) - 1:
                ax.annotate(
                    "",
                    xy=(x + 34, y + 10),
                    xytext=(x + 30, y + 10),
                    arrowprops=dict(arrowstyle="->", color=GOLD, lw=2),
                )

    plate(
        "05-utility-zones",
        "Utility and expansion design requirements",
        lambda ax: chain(
            ax,
            [
                "Utility pathway\n1 MW practical / 2 MW optional\nWill-serve not obtained",
                "Modular critical plant\n250 kW first / 500 kW expanded\n0 kW commissioned",
                "A/B distribution\nEach carries accepted load\nUpstream risk review required",
                "Fiber route A\nSeparate entrance required",
                "Fiber route B\nLast-mile independence unverified",
                "Expansion gate\nDemand + funding + permits\nNo calendar auto-acceptance",
            ],
        ),
    )

    def electrical(ax):
        e = a["technical_design"]["electrical"]
        stage = e["initial"]
        calc = result["technical_design"]["engineering"][0]
        ax.set(xlim=(0, 100), ylim=(0, 90))
        ax.axis("off")
        box(
            ax,
            35,
            74,
            30,
            12,
            f"Shared utility service: {e['service_kw']} kW\n{e['voltage_ll']} V / {e['service_breaker_a']} A concept",
        )
        box(
            ax,
            2,
            70,
            27,
            16,
            f"{stage['generator_count']} x {e['generator_unit_kw']} kW gensets\nN+1 capacity {calc['generation_n1_kw']} kW\nEmergency distribution",
        )
        box(
            ax,
            70,
            70,
            28,
            16,
            f"Peak facility input\n{calc['peak_facility_input_kw']} kW\nIncludes cooling / recharge",
        )
        for x, label in [(12, "A"), (60, "B")]:
            box(
                ax,
                x,
                46,
                28,
                15,
                f"ATS / UPS path {label}\n{stage['ups_modules_per_path']} x {e['ups_module_kw']} kW\n{stage['ups_feeder_a']} A feeder",
            )
            box(
                ax,
                x,
                22,
                28,
                15,
                f"Customer rack PDU {label}\n{e['rack_voltage_ll']} V / {e['rack_feed_a']} A\nFull rack on either feed",
            )
            ax.annotate(
                "",
                xy=(x + 14, 61),
                xytext=(50, 74),
                arrowprops=dict(arrowstyle="->", color=GOLD, lw=2),
            )
            ax.annotate(
                "",
                xy=(x + 14, 37),
                xytext=(x + 14, 46),
                arrowprops=dict(arrowstyle="->", color=TEAL, lw=2),
            )
            ax.annotate(
                "",
                xy=(50, 12),
                xytext=(x + 14, 22),
                arrowprops=dict(arrowstyle="->", color=TEAL, lw=2),
            )
        ax.annotate(
            "",
            xy=(26, 61),
            xytext=(15, 70),
            arrowprops=dict(arrowstyle="->", color=GOLD, linestyle="--"),
        )
        ax.annotate(
            "",
            xy=(74, 61),
            xytext=(15, 70),
            arrowprops=dict(arrowstyle="->", color=GOLD, linestyle="--"),
        )
        box(
            ax,
            32,
            1,
            36,
            12,
            f"{stage['usable_it_kw']} kW usable IT module\nA/B redundancy is not twice the load",
        )

    plate(
        "06-electrical-concept",
        "Owned plant: rated electrical concept",
        electrical,
        "Concept sizing, not a protection/arc-flash study or installation instruction. Shared utility dependency remains. Qualified design and commissioning required.",
    )

    def cooling(ax):
        e = a["technical_design"]["electrical"]
        stage = e["initial"]
        calc = result["technical_design"]["engineering"][0]
        ax.set(xlim=(0, 100), ylim=(0, 75))
        ax.axis("off")
        box(
            ax,
            2,
            49,
            29,
            21,
            f"Heat rejection yard\n{stage['cooling_modules']} x {e['cooling_module_thermal_kw']} kW thermal\nN+1: {calc['cooling_n1_thermal_kw']} kW",
        )
        box(
            ax,
            37,
            49,
            27,
            21,
            "Dual pumping / isolation\nSupply and return headers\nLeak / flow / temperature alarms",
        )
        box(
            ax,
            70,
            49,
            28,
            21,
            f"Contained air rows\nIT + UPS heat: {calc['heat_rejection_kw']} kW\n18–24 C inlet design target",
        )
        for x in (31, 64):
            ax.annotate(
                "",
                xy=(x + 6, 61),
                xytext=(x, 61),
                arrowprops=dict(arrowstyle="->", color=TEAL, lw=2),
            )
            ax.annotate(
                "",
                xy=(x, 56),
                xytext=(x + 6, 56),
                arrowprops=dict(arrowstyle="->", color=GOLD, lw=2),
            )
        box(
            ax,
            2,
            8,
            29,
            23,
            f"Peak cooling electrical input\n{calc['cooling_input_kw']} kW at COP {e['cooling_design_cop']}\nAnnual PUE is a different boundary",
        )
        box(
            ax,
            37,
            8,
            27,
            23,
            "Future liquid row only\nIsolated CDU / facility loop\nNo direct supplier loop connection",
        )
        box(
            ax,
            70,
            8,
            28,
            23,
            "Expanded 500 kW stage\n5 x 150 kW thermal modules\nN+1 = 600 kW; 520 kW heat",
        )

    plate(
        "07-cooling-concept",
        "Owned plant: air baseline and future liquid path",
        cooling,
        "Source-rated concept. Actual altitude, equipment inlet range, coolant compatibility, hydraulics and heat rejection require qualified acceptance.",
    )
    for site_id, name, num in [
        ("RENO", "Switch customer-enclosure requirement", 8),
        ("BOISE", "Boise customer-enclosure requirement", 9),
    ]:
        size = next(
            x
            for x in result["capacity"]
            if x["year"] == 2027 and x["scenario"] == "base" and x["site"] == site_id
        )

        def enclosure(ax, size=size):
            e = a["technical_design"]["enclosure"]
            per_row = min(size["racks"], e["maximum_racks_per_row"])
            rows = math.ceil(size["racks"] / per_row)
            aisle = e["aisle_m"]
            depth = e["cabinet_depth_m"]
            pitch = e["cabinet_pitch_m"]
            width = per_row * pitch + 2 * aisle
            height = rows * depth + (rows + 1) * aisle
            ax.set(xlim=(0, width), ylim=(0, height), aspect="equal")
            ax.set_xlabel("Concept metres")
            ax.set_ylabel("Concept metres")
            ax.add_patch(
                Rectangle(
                    (0, 0), width, height, facecolor="#fff3d6", edgecolor=TEAL, lw=2
                )
            )
            for n, rack in enumerate(size["rack_placements"]):
                x = aisle + (n % per_row) * pitch
                y = aisle + (n // per_row) * (depth + aisle)
                ax.add_patch(
                    Rectangle(
                        (x, y),
                        e["cabinet_width_m"],
                        depth,
                        facecolor=PALE,
                        edgecolor=TEAL,
                    )
                )
                ax.text(
                    x + e["cabinet_width_m"] / 2,
                    y + depth / 2,
                    f"R{n + 1}\n{rack['u']}U\n{rack['peak_kw']:.2f}kW",
                    ha="center",
                    va="center",
                    fontsize=6,
                )
            ax.text(
                width / 2,
                height - aisle / 2,
                f"{size['racks']} cabinets; {size['peak_kw']} kW peak; {aisle} m clear-aisle concept",
                ha="center",
                fontsize=9,
            )
            ax.text(
                width / 2,
                aisle / 2,
                "Separate controlled access, A/B feeds and management paths",
                ha="center",
                fontsize=8,
            )

        plate(f"{num:02}-enclosure-{site_id.lower()}", name, enclosure)

    def elevation(ax):
        size = next(
            x
            for x in result["capacity"]
            if x["year"] == 2027 and x["scenario"] == "base" and x["site"] == "RENO"
        )
        racks = size["rack_placements"]
        ax.set(xlim=(0, len(racks) * 10), ylim=(0, 42))
        ax.set_ylabel("Rack unit")
        ax.set_xticks([])
        for n, rack in enumerate(racks):
            x = n * 10
            ax.add_patch(Rectangle((x, 0), 9, 36, facecolor=PALE, edgecolor=TEAL))
            ax.text(x + 4.5, 40, rack["id"], ha="center", fontsize=6)
            ax.text(x + 4.5, 37, f"{rack['peak_kw']:.1f} kW", ha="center", fontsize=6)
            for item in rack["equipment"]:
                y = item["first_u"] - 1
                ax.add_patch(
                    Rectangle((x, y), 9, item["u"], facecolor="#c4dedb", edgecolor=TEAL)
                )
                ax.text(
                    x + 4.5,
                    y + item["u"] / 2,
                    item["id"].replace("NETWORK_HSM", "NET"),
                    ha="center",
                    va="center",
                    fontsize=5,
                )

    plate(
        "10-rack-elevations",
        "Reno base case: equipment placement by rack",
        elevation,
        "Source-driven configuration classes; no assigned provider cabinets. Each A/B feed carries full rack load. Vendor, thermal and installation acceptance pending.",
    )
    plate(
        "11-logical-boundaries",
        "Logical, management and recovery planes",
        lambda ax: chain(
            ax,
            [
                "Enterprise shared plane\nIdentity / DNS / time",
                "Policy enforcement\nBefore retrieval/model context",
                "Restricted Alexandria\nJ2 content authority",
                "Atlas / Foundry tenant planes\nProduct authority retained",
                "Separate OOB + vault\nIndependent keys and identities",
                "Boise bootstrap / restore\nOffline runbooks + tombstones",
            ],
        ),
    )

    def schedule(ax):
        phases = [p for p in a["phases"] if p["id"] != "RT-CONTINGENCY"]
        import matplotlib.dates as md
        from datetime import date

        for n, p in enumerate(phases):
            start = md.date2num(date.fromisoformat(p["start"]))
            end = md.date2num(date.fromisoformat(p["end"]))
            ax.barh(
                n,
                max(2, end - start),
                left=start,
                color=TEAL if p["actual_completion"] else GOLD,
            )
        ax.set_yticks(range(len(phases)), [p["id"] for p in phases])
        ax.invert_yaxis()
        ax.xaxis_date()
        ax.xaxis.set_major_formatter(md.DateFormatter("%Y-%m"))
        ax.grid(axis="x", alpha=0.2)
        ax.text(
            0.02,
            -0.14,
            "Teal: synthetic acquired land. Gold: conditional forecast / authorized scope, not completion.",
            transform=ax.transAxes,
            fontsize=9,
        )

    plate(
        "12-construction-schedule",
        "Construction forecast and accepted land event",
        schedule,
    )
    (output / "manifest.json").write_text(
        json.dumps(
            {
                "source_sha256": result["source_sha256"],
                "classification": "SYNTHETIC_CONCEPT_NOT_AS_BUILT",
                "files": {
                    p.name: hashlib.sha256(p.read_bytes()).hexdigest() for p in paths
                },
            },
            indent=2,
        )
        + "\n"
    )


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, required=True)
    build(parser.parse_args().output)
